'use client';

import React, { useState } from 'react';
import {
  Search,
  ChevronDown,
  CheckCircle2,
  Lock,
  Copy,
  Check,
  ArrowRight,
  Headphones,
  FileCheck2,
  Key,
  Sparkles,
  Zap,
} from 'lucide-react';

interface FaqItem {
  id: string;
  question: string;
  category: string;
  paragraphs: string[];
  badges?: string[];
}

const FAQ_ITEMS: FaqItem[] = [
  {
    id: 'faq-1',
    category: 'Consensus & DAG',
    question: 'How does OmniVise guarantee zero hallucination in decision syntheses?',
    paragraphs: [
      'OmniVise operates on a strict deterministic ground-truth anchoring paradigm. Unlike conventional generative AI systems, claim generation is bounded to exact mathematical token offsets in ingested primary documents (PDFs, SEC EDGAR 10-K/Q filings, call transcripts).',
      'Every synthesized deduction requires dual-channel witness corroboration. If an asserted fact or valuation delta cannot resolve back to an immutable raw chunk with an unblemished SHA-256 hash stamp, the claim is algorithmically flagged as an unanchored hypothesis and rejected from the final signed decision ledger.',
    ],
    badges: ['Deterministic Offsets', 'Dual-Witness Protocol', 'Audit Compliant'],
  },
  {
    id: 'faq-2',
    category: 'Hardware Security & HSM',
    question: 'What are the exact FIPS 140-3 Level 4 hardware token requirements?',
    paragraphs: [
      'OmniVise requires physical security keys adhering to FIPS 140-3 Level 3 or Level 4 cryptographic standards (e.g. YubiKey 5 Series, Nitrokey 3, or institutional smartcards). Keys must support WebAuthn / FIDO2 with user verification via PIN or biometric presence.',
      'During session authorization and critical decision gates, ECDSA P-384 counter-signatures are evaluated directly on the hardware enclave without exposing private seeds to client memory.',
    ],
    badges: ['FIPS 140-3 L4', 'ECDSA P-384', 'WebAuthn'],
  },
  {
    id: 'faq-3',
    category: 'Ingestion Protocols',
    question: 'How are contradictory claims and statutory accounting divergences isolated?',
    paragraphs: [
      'During Stage 3 of our ingestion pipeline, claims extracted from distinct document types (e.g. 10-Q filing notes vs. corporate earnings audio transcripts) are mapped into a bipartite causal lattice.',
      'When two claims share identical semantic scopes (such as FY2026 Operating Margin) but diverge in quantitative magnitude, an automated adversarial inquest calculates the delta. Discrepancies exceeding the configured materiality threshold ($500k by default) trigger consensus holds.',
    ],
    badges: ['Bipartite Lattice', 'Ablation Testing', 'ASC 606 Awareness'],
  },
  {
    id: 'faq-4',
    category: 'API & Webhooks',
    question: 'Can we integrate automated webhook feeds from internal ERP and Bloomberg terminals?',
    paragraphs: [
      'Yes. OmniVise provides mutual-TLS authenticated streaming endpoints for SAP S/4HANA, Oracle NetSuite, Workday, and Bloomberg Terminal B-PIPE. Documents and tabular dumps pushed to `/api/v1/ingest/stream` are cryptographically time-stamped and parsed in sub-second cycles.',
    ],
    badges: ['mTLS Webhooks', 'ERP Ingestion', 'Streaming Pipeline'],
  },
  {
    id: 'faq-5',
    category: 'Consensus & DAG',
    question: 'How does the Robustness Score calculate ablation sensitivity?',
    paragraphs: [
      'The Robustness Score evaluates decision stability under synthetic counterfactuals. The engine progressively masks individual evidence nodes in the DAG and re-executes verification. High robustness (>95%) confirms conclusions do not rely on fragile single-source assertions.',
    ],
    badges: ['Sensitivity Index', 'Monte Carlo Stress', 'Robustness >95%'],
  },
  {
    id: 'faq-6',
    category: 'Audit Dossiers',
    question: 'What happens when an air-gap or local session purge is triggered?',
    paragraphs: [
      'Executing a purge immediately zeroes all ephemeral session tokens, vector indexes in browser memory, and unanchored query buffers. Only cryptographically sealed and counter-signed DAG hashes persisted in the distributed ledger remain intact.',
    ],
    badges: ['Zero-Data Retention', 'Memory Zeroing', 'Air-Gap Safe'],
  },
  {
    id: 'faq-7',
    category: 'Audit Dossiers',
    question: 'How do regulatory auditors verify the exported PDF dossier?',
    paragraphs: [
      'Every PDF generated by OmniVise contains an embedded cryptographic manifest with SHA-256 digests of all referenced primary sources, alongside the cryptographic signatures of reviewing analysts. Auditors can independently verify integrity using our open-source CLI verifier.',
    ],
    badges: ['Embedded Manifest', 'Independent Audit', 'CLI Verifier'],
  },
];

const TOPIC_FILTERS = [
  'All Topics',
  'Ingestion Protocols',
  'Consensus & DAG',
  'Hardware Security & HSM',
  'Audit Dossiers',
  'API & Webhooks',
];

export default function HelpPage() {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeFilter, setActiveFilter] = useState('All Topics');
  const [expandedFaqs, setExpandedFaqs] = useState<Record<string, boolean>>({
    'faq-1': true,
  });
  const [copiedFingerprint, setCopiedFingerprint] = useState(false);
  const [formSubmitted, setFormSubmitted] = useState(false);

  const [ticketState, setTicketState] = useState({
    name: 'Elena Rostova',
    email: 'elena.r@omnivise.institutional',
    priority: 'Priority 1 - Critical Divergence',
    category: 'Consensus divergence in SEC 10-Q filing',
    enquiry:
      '[WARN] Node_22: Divergence threshold exceeded ($1.4M Delta vs 10-Q Item 1).\n[ERR] Hardware Token (YubiKey 5C) reported timeout during ECDSA P-384 counter-sign.\nRequesting verification of the enclave leaf state.',
    attachTelemetry: true,
  });

  const toggleFaq = (id: string) => {
    setExpandedFaqs((prev) => ({
      ...prev,
      [id]: !prev[id],
    }));
  };

  const handleExpandAll = () => {
    const allExpanded = Object.keys(expandedFaqs).length === FAQ_ITEMS.length;
    if (allExpanded) {
      setExpandedFaqs({});
    } else {
      const next: Record<string, boolean> = {};
      FAQ_ITEMS.forEach((f) => {
        next[f.id] = true;
      });
      setExpandedFaqs(next);
    }
  };

  const handleCopyFingerprint = () => {
    navigator.clipboard.writeText('5B2F 9903 CB51 C618 7AA3 F61B 008D C18E');
    setCopiedFingerprint(true);
    setTimeout(() => setCopiedFingerprint(false), 2000);
  };

  const handleSubmitTicket = (e: React.FormEvent) => {
    e.preventDefault();
    setFormSubmitted(true);
    setTimeout(() => setFormSubmitted(false), 5000);
  };

  const filteredFaqs = FAQ_ITEMS.filter((item) => {
    const matchesFilter =
      activeFilter === 'All Topics' || item.category === activeFilter;
    const matchesSearch =
      searchQuery.trim() === '' ||
      item.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.paragraphs.some((p) =>
        p.toLowerCase().includes(searchQuery.toLowerCase())
      );
    return matchesFilter && matchesSearch;
  });

  return (
    <div className="space-y-10 animate-fadeIn max-w-[1360px] mx-auto pb-10">
      {/* Top Banner & Header */}
      <div className="space-y-3 pb-2">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-[#E8F6F2] text-[#0B5C48] border border-[#C6ECE0] text-[11px] font-bold tracking-wider uppercase shadow-xs">
          <span className="w-2 h-2 rounded-full bg-[#0B5C48]" />
          <span>Knowledge Repository &middot; v4.2.0 &middot; FIPS Compliant Guidance</span>
        </div>

        <h1 className="text-3xl sm:text-4xl font-sans font-bold text-slate-900 tracking-tight">
          Help &amp; Institutional Documentation
        </h1>
        <p className="text-sm text-slate-500 max-w-3xl leading-relaxed">
          Comprehensive guides, cryptographic methodology, protocol FAQs, and direct access to dedicated cryptographic support engineers.
        </p>
      </div>

      {/* Search Bar & Filter Chips */}
      <div className="bg-white rounded-3xl p-6 border border-slate-200/80 shadow-xs space-y-4">
        <div className="relative">
          <Search className="w-4 h-4 text-slate-400 absolute left-4 top-3.5 pointer-events-none" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search guides, DAG algorithms, verification gates, or error codes (e.g. 'FIPS-140-3', 'divergence threshold')..."
            className="w-full pl-11 pr-14 py-3 bg-[#F8FAFC] border border-slate-200 text-slate-900 text-xs sm:text-sm rounded-2xl focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#0B5C48]/10 focus:border-[#0B5C48] transition-all placeholder:text-slate-400"
          />
          <span className="absolute right-4 top-3 bg-white border border-slate-200 text-slate-500 font-mono text-xs font-semibold px-2 py-0.5 rounded-lg shadow-2xs">
            &amp;#8984;K
          </span>
        </div>

        {/* Filter Pills */}
        <div className="flex items-center gap-2 overflow-x-auto no-scrollbar pt-1">
          <span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider mr-1 shrink-0">
            Filters:
          </span>
          {TOPIC_FILTERS.map((filter) => (
            <button
              key={filter}
              type="button"
              onClick={() => setActiveFilter(filter)}
              className={`px-3.5 py-1.5 rounded-full text-xs font-semibold transition-all whitespace-nowrap ${
                activeFilter === filter
                  ? 'bg-[#0B5C48] text-white shadow-xs'
                  : 'bg-white border border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-slate-50'
              }`}
            >
              {filter}
            </button>
          ))}
        </div>
      </div>

      {/* Architecture Overview Section */}
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <span className="bg-emerald-50 text-[#0B5C48] border border-emerald-200 text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider">
            Architecture Overview
          </span>
          <span className="text-xs text-slate-400 font-medium">High Assurance Pipeline</span>
        </div>

        <div>
          <h2 className="text-xl font-bold text-slate-900 font-sans tracking-tight">
            How OmniVise Cryptographic Evidence Verification Works
          </h2>
          <p className="text-xs text-slate-500 mt-1 leading-relaxed">
            Four deterministic stages transforming raw multi-modal information into tamper-proof, auditable decisions.
          </p>
        </div>

        {/* 4 Pipeline Stage Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 pt-1">
          {/* Stage 01 */}
          <div className="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-xs flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-[10px] font-mono font-bold text-slate-400 uppercase tracking-wider">
                  STAGE 01
                </span>
                <div className="w-7 h-7 rounded-lg bg-[#EBF3FF] text-[#2563EB] flex items-center justify-center">
                  <FileCheck2 className="w-3.5 h-3.5" />
                </div>
              </div>
              <h3 className="text-sm font-bold text-slate-900 font-sans mb-1.5 leading-snug">
                Multi-Modal Ingestion &amp; Diarization
              </h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Ingest unstructured PDFs, audio records, regulatory filings, and live streams with zero-knowledge SHA-256 chunking and vector pinning.
              </p>
            </div>
            <div className="pt-3 border-t border-slate-100 flex items-center justify-between text-[11px]">
              <div className="flex items-center gap-1.5 text-slate-600">
                <span className="w-1.5 h-1.5 rounded-full bg-[#0B5C48]" />
                <span>ZK-Proof Pinning</span>
              </div>
              <span className="font-mono text-slate-500 font-semibold">Sub-10ms</span>
            </div>
          </div>

          {/* Stage 02 */}
          <div className="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-xs flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-[10px] font-mono font-bold text-slate-400 uppercase tracking-wider">
                  STAGE 02
                </span>
                <div className="w-7 h-7 rounded-lg bg-[#E6F8F3] text-[#0B5C48] flex items-center justify-center">
                  <Sparkles className="w-3.5 h-3.5" />
                </div>
              </div>
              <h3 className="text-sm font-bold text-slate-900 font-sans mb-1.5 leading-snug">
                Deterministic Grounding &amp; Corroboration
              </h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Multi-model consensus engines evaluate claims against primary sources without generative hallucination drift.
              </p>
            </div>
            <div className="pt-3 border-t border-slate-100 flex items-center justify-between text-[11px]">
              <div className="flex items-center gap-1.5 text-slate-600">
                <span className="w-1.5 h-1.5 rounded-full bg-[#0B5C48]" />
                <span>Double-Witnessed</span>
              </div>
              <span className="font-mono text-slate-500 font-semibold">0% Generative Drift</span>
            </div>
          </div>

          {/* Stage 03 */}
          <div className="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-xs flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-[10px] font-mono font-bold text-slate-400 uppercase tracking-wider">
                  STAGE 03
                </span>
                <div className="w-7 h-7 rounded-lg bg-amber-50 text-amber-600 flex items-center justify-center">
                  <Zap className="w-3.5 h-3.5" />
                </div>
              </div>
              <h3 className="text-sm font-bold text-slate-900 font-sans mb-1.5 leading-snug">
                Adversarial Stress &amp; Divergence Inquest
              </h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Algorithmic testing across counterfactuals, isolating statutory vs. operational divergences with ablation sensitivity scoring.
              </p>
            </div>
            <div className="pt-3 border-t border-slate-100 flex items-center justify-between text-[11px]">
              <div className="flex items-center gap-1.5 text-slate-600">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-500" />
                <span>Ablation Models</span>
              </div>
              <span className="font-mono text-slate-500 font-semibold">Delta &gt; $500k Trigger</span>
            </div>
          </div>

          {/* Stage 04 */}
          <div className="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-xs flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-[10px] font-mono font-bold text-slate-400 uppercase tracking-wider">
                  STAGE 04
                </span>
                <div className="w-7 h-7 rounded-lg bg-[#EFF6FF] text-[#2563EB] flex items-center justify-center">
                  <Lock className="w-3.5 h-3.5" />
                </div>
              </div>
              <h3 className="text-sm font-bold text-slate-900 font-sans mb-1.5 leading-snug">
                Cryptographic DAG Sealing &amp; Sign-Off
              </h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Hardware-enforced FIPS 140-3 PKI multi-sig sealing, creating immutable decision dossiers ready for regulatory audit.
              </p>
            </div>
            <div className="pt-3 border-t border-slate-100 flex items-center justify-between text-[11px]">
              <div className="flex items-center gap-1.5 text-slate-600">
                <span className="w-1.5 h-1.5 rounded-full bg-[#0B5C48]" />
                <span>FIPS 140-3 HSM</span>
              </div>
              <span className="font-mono text-slate-500 font-semibold">ECDSA P-384</span>
            </div>
          </div>
        </div>
      </div>

      {/* Frequently Asked Questions */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <h2 className="text-xl font-bold text-slate-900 font-sans tracking-tight">
              Frequently Asked Questions
            </h2>
            <span className="bg-[#F1F5F9] text-slate-600 text-xs font-semibold px-2.5 py-0.5 rounded-full border border-slate-200">
              {filteredFaqs.length} Verified Articles
            </span>
          </div>
          <button
            type="button"
            onClick={handleExpandAll}
            className="text-xs font-semibold text-[#0B5C48] hover:underline"
          >
            {Object.keys(expandedFaqs).length === FAQ_ITEMS.length
              ? 'Collapse All'
              : 'Expand All'}
          </button>
        </div>

        {/* Accordion Cards */}
        <div className="space-y-3">
          {filteredFaqs.map((faq) => {
            const isExpanded = !!expandedFaqs[faq.id];

            return (
              <div
                key={faq.id}
                className="bg-white rounded-2xl border border-slate-200/80 shadow-xs overflow-hidden transition-all"
              >
                <button
                  type="button"
                  onClick={() => toggleFaq(faq.id)}
                  className="w-full px-6 py-4 flex items-center justify-between gap-4 text-left focus:outline-none hover:bg-slate-50/50 transition-colors"
                >
                  <span className="text-sm font-bold text-slate-900 leading-snug">
                    {faq.question}
                  </span>
                  <div className="w-6 h-6 rounded-full bg-[#F8FAFC] border border-slate-200 flex items-center justify-center shrink-0">
                    <ChevronDown
                      className={`w-3.5 h-3.5 text-slate-500 transition-transform duration-200 ${
                        isExpanded ? 'rotate-180' : ''
                      }`}
                    />
                  </div>
                </button>

                {isExpanded && (
                  <div className="px-6 pb-5 pt-1 space-y-3 text-xs text-slate-600 leading-relaxed border-t border-slate-100/80">
                    {faq.paragraphs.map((p, idx) => (
                      <p key={idx}>{p}</p>
                    ))}

                    {faq.badges && (
                      <div className="flex items-center gap-2 flex-wrap pt-2">
                        {faq.badges.map((b) => (
                          <span
                            key={b}
                            className="bg-[#F1F5F9] text-slate-700 text-[10px] font-semibold px-2.5 py-1 rounded-md border border-slate-200"
                          >
                            {b}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Secure Escalation Section */}
      <div className="space-y-4 pt-4">
        <div className="flex items-center gap-2">
          <span className="bg-amber-50 text-amber-800 border border-amber-200 text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider">
            Secure Escalation
          </span>
          <span className="text-xs text-slate-400 font-medium">L3 Cryptographic Engineering Enclave</span>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left Enclave Support Card (5 cols) */}
          <div className="lg:col-span-5 bg-white rounded-3xl p-6 border border-slate-200/80 shadow-xs space-y-5 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <div className="w-9 h-9 rounded-xl bg-[#E6F8F3] text-[#0B5C48] flex items-center justify-center shrink-0">
                  <Headphones className="w-4 h-4" />
                </div>
                <div>
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="text-sm font-bold text-slate-900">
                      Dedicated Enclave Support
                    </h3>
                  </div>
                  <span className="inline-flex items-center gap-1.5 text-[10px] text-[#0B5C48] font-bold mt-0.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#0B5C48] animate-pulse" />
                    24/7 Priority SLA &lt;15 Mins
                  </span>
                </div>
              </div>

              <p className="text-xs text-slate-500 leading-relaxed">
                Institutional analysts have unmediated access to our cryptographic systems engineers. Critical priority escalations trigger immediate war-room dispatch for HSM anomalies, consensus halts, or vector corruption.
              </p>

              {/* Assigned Account Lead Box */}
              <div className="p-3.5 bg-[#F8FAFC] border border-slate-200/80 rounded-2xl space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                    Assigned Account Lead
                  </span>
                  <span className="bg-[#E6F8F3] text-[#0B5C48] text-[10px] font-bold px-2 py-0.5 rounded-full">
                    Active
                  </span>
                </div>
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-slate-900 text-white font-bold text-xs flex items-center justify-center">
                    MV
                  </div>
                  <div>
                    <h4 className="text-xs font-bold text-slate-900">Marcus Vance</h4>
                    <p className="text-[11px] text-slate-500">Principal Cryptographic Engineer</p>
                  </div>
                </div>
              </div>

              {/* PGP Fingerprint Box */}
              <div className="p-3.5 bg-[#F8FAFC] border border-slate-200/80 rounded-2xl space-y-1.5">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-700">
                    <Key className="w-3.5 h-3.5 text-amber-600" />
                    <span>Enclave PGP Fingerprint</span>
                  </div>
                  <button
                    type="button"
                    onClick={handleCopyFingerprint}
                    className="text-[10px] font-semibold text-[#0B5C48] hover:underline flex items-center gap-1"
                  >
                    {copiedFingerprint ? (
                      <>
                        <Check className="w-3 h-3" /> Copied
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3" /> Copy
                      </>
                    )}
                  </button>
                </div>
                <p className="font-mono text-[10px] text-slate-500 tracking-wider">
                  5B2F 9903 CB51 C618 7AA3 F61B 008D C18E
                </p>
              </div>
            </div>

            {/* Direct Bridge Phone */}
            <div className="pt-3 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500">
              <div className="flex items-center gap-2">
                <Lock className="w-3.5 h-3.5 text-slate-400" />
                <span>Direct Bridge: +1 (800) 555-OMNI (ext. 4)</span>
              </div>
              <span className="text-[10px] font-bold text-[#0B5C48] bg-[#E6F8F3] px-2 py-0.5 rounded">
                Secure Line
              </span>
            </div>
          </div>

          {/* Right Ticket Form (7 cols) */}
          <div className="lg:col-span-7 bg-white rounded-3xl p-6 sm:p-7 border border-slate-200/80 shadow-xs space-y-4">
            {formSubmitted ? (
              <div className="p-8 text-center space-y-3 bg-[#E6F8F3] border border-[#BCEEE2] rounded-2xl my-auto">
                <div className="w-10 h-10 rounded-full bg-[#0B5C48] text-white flex items-center justify-center mx-auto">
                  <CheckCircle2 className="w-5 h-5" />
                </div>
                <h3 className="text-sm font-bold text-[#0B5C48]">Support Dossier Dispatched</h3>
                <p className="text-xs text-slate-600 max-w-sm mx-auto leading-relaxed">
                  Incident ticket #OMNI-9942 opened with high-priority priority queue. Lead Marcus Vance has been notified.
                </p>
              </div>
            ) : (
              <form onSubmit={handleSubmitTicket} className="space-y-4" noValidate>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[10px] font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                      Analyst Name
                    </label>
                    <div className="relative">
                      <input
                        type="text"
                        value={ticketState.name}
                        onChange={(e) =>
                          setTicketState({ ...ticketState, name: e.target.value })
                        }
                        className="w-full px-3.5 py-2.5 bg-[#F8FAFC] border border-slate-200 text-slate-900 text-xs rounded-xl focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#0B5C48]/10 focus:border-[#0B5C48]"
                      />
                      <CheckCircle2 className="w-3.5 h-3.5 text-[#0B5C48] absolute right-3.5 top-3" />
                    </div>
                  </div>

                  <div>
                    <label className="block text-[10px] font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                      Institutional Email
                    </label>
                    <input
                      type="email"
                      value={ticketState.email}
                      onChange={(e) =>
                        setTicketState({ ...ticketState, email: e.target.value })
                      }
                      className="w-full px-3.5 py-2.5 bg-[#F8FAFC] border border-slate-200 text-slate-900 text-xs rounded-xl focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#0B5C48]/10 focus:border-[#0B5C48]"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[10px] font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                      Urgency / Priority Level
                    </label>
                    <select
                      value={ticketState.priority}
                      onChange={(e) =>
                        setTicketState({ ...ticketState, priority: e.target.value })
                      }
                      className="w-full px-3.5 py-2.5 bg-[#F8FAFC] border border-slate-200 text-slate-900 text-xs rounded-xl focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#0B5C48]/10 focus:border-[#0B5C48]"
                    >
                      <option>Priority 1 - Critical Divergence</option>
                      <option>Priority 2 - High Materiality Finding</option>
                      <option>Priority 3 - General Operational Inquiry</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-[10px] font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                      Subject / Incident Category
                    </label>
                    <input
                      type="text"
                      value={ticketState.category}
                      onChange={(e) =>
                        setTicketState({ ...ticketState, category: e.target.value })
                      }
                      className="w-full px-3.5 py-2.5 bg-[#F8FAFC] border border-slate-200 text-slate-900 text-xs rounded-xl focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#0B5C48]/10 focus:border-[#0B5C48]"
                    />
                  </div>
                </div>

                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label className="block text-[10px] font-bold text-slate-700 uppercase tracking-wider">
                      Detailed Enquiry or Error Log
                    </label>
                    <span className="text-[10px] text-slate-400 font-mono">
                      Markdown / Monospace enabled
                    </span>
                  </div>
                  <textarea
                    rows={4}
                    value={ticketState.enquiry}
                    onChange={(e) =>
                      setTicketState({ ...ticketState, enquiry: e.target.value })
                    }
                    className="w-full px-3.5 py-2.5 bg-[#F8FAFC] border border-slate-200 text-slate-900 font-mono text-xs rounded-xl focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#0B5C48]/10 focus:border-[#0B5C48] leading-relaxed resize-y"
                  />
                </div>

                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-1">
                  <label className="flex items-center gap-2 text-xs text-slate-600 cursor-pointer select-none">
                    <input
                      type="checkbox"
                      checked={ticketState.attachTelemetry}
                      onChange={(e) =>
                        setTicketState({
                          ...ticketState,
                          attachTelemetry: e.target.checked,
                        })
                      }
                      className="w-4 h-4 rounded border-slate-300 text-[#0B5C48] focus:ring-[#0B5C48] accent-[#0B5C48]"
                    />
                    <span>Attach Diagnostic Telemetry Bundle (Sanitized)</span>
                  </label>

                  <button
                    type="submit"
                    className="px-6 py-2.5 bg-[#0B5C48] hover:bg-[#084838] active:bg-[#06392c] text-white text-xs font-semibold rounded-xl flex items-center justify-center gap-2 shadow-sm transition-colors cursor-pointer"
                  >
                    <span>Submit Support Dossier</span>
                    <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}